#!/bin/bash
#SBATCH -J 2lfx
#SBATCH -p general
#SBATCH -o filename_%j.txt
#SBATCH -e filename_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=username@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --time=01:00:00

cd /N/project/MIM_NMR_CATALYSIS/MIM_NA_NMR/ML/combined/xtb
export XTB_DIR=/N/project/MIM_NMR_CATALYSIS/MIM_NA_NMR/ML/combined/xtb
/N/u/schandy/BigRed3/bin/xtb-6.5.1/bin/xtb  2lfx.xyz --alpb water  > 2lfx.alpb.out
/N/u/schandy/BigRed3/bin/xtb-6.5.1/bin/xtb  2lfx.xyz --gbsa water > 2lfx.gbsa.out

